# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7defdf51e6e0c743037a8e8780bf1e719e0f9242abf5e5b9ce522dc39d2160cdbcadf4f91fd94eab19b9cfa5de6129030740b96be305f41cd5477e1e794a083

test:
  secret_key_base: 18470ddfc9acd727feda85c26f8e202fa6fb839fa7f1c5624605d981cc5ce62b93df5275e6b07701db01f2e1bf37be2aa24f8125d9626e9734c0b864aaecd824

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
